'use client'

import Link from 'next/link'
import { ArrowRight, Banknote, Building2, Check, ChevronRight, CircleHelp, FileCheck2, Gavel, Handshake, Menu, ShieldCheck, Sparkles, Target, X } from 'lucide-react'
import { useState } from 'react'

export function Logo() {
  return <Link href="/" className="flex items-center gap-2.5 font-semibold tracking-tight"><span className="grid h-8 w-8 place-items-center rounded-[10px] bg-primary text-primary-foreground shadow-[0_0_24px_oklch(.76_.17_165_/_25%)]"><span className="text-lg italic">S</span></span><span className="text-[17px] text-foreground">Settle<span className="text-red-600">X</span></span></Link>
}

export function Navbar() {
  const [open, setOpen] = useState(false)
  return <header className="relative z-20 mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><Logo /><nav className="hidden items-center gap-7 text-sm text-muted-foreground md:flex"><Link href="/how-it-works" className="transition hover:text-foreground">How it works</Link><Link href="/borrower" className="transition hover:text-foreground">Borrower</Link><Link href="/lender" className="transition hover:text-foreground">Lender</Link></nav><div className="hidden items-center gap-3 md:flex"><Link href="/negotiation" className="rounded-full border border-border px-4 py-2 text-sm text-muted-foreground transition hover:border-primary/50 hover:text-foreground">View demo</Link><Link href="/borrower" className="rounded-full bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground transition hover:brightness-110">Start negotiation</Link></div><button onClick={() => setOpen(!open)} className="rounded-lg border border-border p-2 md:hidden" aria-label="Toggle menu">{open ? <X size={18}/> : <Menu size={18}/>}</button>{open && <div className="absolute left-5 right-5 top-16 rounded-2xl border border-border bg-card p-4 shadow-2xl md:hidden"><div className="grid gap-3 text-sm"><Link href="/how-it-works">How it works</Link><Link href="/borrower">Borrower setup</Link><Link href="/lender">Lender setup</Link><Link href="/negotiation" className="text-primary">Open demo</Link></div></div>}</header>
}

export function Shell({ children, eyebrow, title, description }: { children: React.ReactNode; eyebrow?: string; title?: string; description?: string }) { return <main className="min-h-screen overflow-hidden"><Navbar />{title && <div className="mx-auto max-w-7xl px-5 pb-8 pt-10 lg:px-8"><p className="mb-3 text-xs font-semibold uppercase tracking-[.22em] text-primary">{eyebrow}</p><h1 className="max-w-3xl text-4xl font-semibold tracking-[-.04em] sm:text-5xl">{title}</h1>{description && <p className="mt-4 max-w-2xl text-base leading-7 text-muted-foreground">{description}</p>}</div>}{children}</main> }

export function AgentCard({ type, status = 'Negotiating' }: { type: 'borrower' | 'lender'; status?: string }) { const borrower = type === 'borrower'; return <div className={`glass rounded-2xl p-5 ${borrower ? 'border-primary/20' : 'border-sky-300/15'}`}><div className="flex items-start justify-between"><div className={`grid h-11 w-11 place-items-center rounded-xl ${borrower ? 'bg-primary/12 text-primary' : 'bg-sky-300/12 text-sky-300'}`}>{borrower ? <ShieldCheck size={22}/> : <Building2 size={22}/>}</div><span className="flex items-center gap-2 text-xs text-primary"><span className="pulse-dot h-1.5 w-1.5 rounded-full bg-primary"/>{status}</span></div><p className="mt-7 text-[11px] font-semibold uppercase tracking-[.18em] text-muted-foreground">{borrower ? 'Borrower advocate' : 'Lender advocate'}</p><h3 className="mt-1 text-xl font-medium">{borrower ? 'Protecting affordability' : 'Optimizing return & risk'}</h3><p className="mt-2 text-sm text-muted-foreground">{borrower ? 'Prioritizing liquidity, flexibility, and sustainable repayment.' : 'Balancing yield, risk exposure, and downside protection.'}</p></div> }

export function UtilityCard({ label, value, accent = 'primary' }: { label: string; value: string; accent?: 'primary' | 'sky' | 'violet' }) { return <div className="glass rounded-xl p-4"><p className="text-xs text-muted-foreground">{label}</p><p className={`mt-2 text-2xl font-semibold ${accent === 'sky' ? 'text-sky-300' : accent === 'violet' ? 'text-violet-300' : 'text-primary'}`}>{value}</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/7"><div className={`h-full rounded-full ${accent === 'sky' ? 'bg-sky-300' : accent === 'violet' ? 'bg-violet-300' : 'bg-primary'}`} style={{ width: `${Number.parseFloat(value) * 100 || 72}%` }}/></div></div> }

export function ProgressIndicator({ current = 3, total = 6 }: { current?: number; total?: number }) { return <div className="flex items-center gap-3 text-xs text-muted-foreground"><span>Round {current} of {total}</span><div className="flex flex-1 gap-1">{Array.from({length: total}).map((_, i) => <span key={i} className={`h-1.5 flex-1 rounded-full ${i < current ? 'bg-primary' : 'bg-white/10'}`}/>)}</div></div> }

export function Verifier() { const checks = ['EMI within borrower affordability limit', 'Interest rate within allowed range', 'Tenure within lender policy', 'No hard constraint violations', 'Agreement mathematically valid']; return <div className="glass rounded-2xl p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-primary"><FileCheck2 size={19}/><p className="text-xs font-semibold uppercase tracking-[.18em]">Financial verifier</p></div><p className="mt-2 text-sm text-muted-foreground">Deterministic validation layer · last checked just now</p></div><span className="rounded-full bg-primary/12 px-3 py-1 text-xs font-semibold text-primary">PASSED</span></div><div className="mt-5 grid gap-2 sm:grid-cols-2">{checks.map((check) => <div key={check} className="flex items-center gap-2 rounded-lg bg-white/[.025] px-3 py-2.5 text-sm text-muted-foreground"><Check size={15} className="shrink-0 text-primary"/>{check}</div>)}</div></div> }

export function ConstraintCard({ title, items }: { title: string; items: string[] }) { return <div className="glass rounded-2xl p-5"><div className="flex items-center gap-2 text-sm font-semibold"><Target size={16} className="text-primary"/>{title}</div><div className="mt-4 space-y-3">{items.map((item) => <div key={item} className="flex items-center justify-between border-b border-border pb-3 text-sm last:border-0 last:pb-0"><span className="text-muted-foreground">{item.split(':')[0]}</span><span className="font-medium">{item.split(':').slice(1).join(':')}</span></div>)}</div></div> }

export function SectionHeading({ eyebrow, title, children }: { eyebrow: string; title: string; children?: React.ReactNode }) { return <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-primary">{eyebrow}</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.035em] sm:text-4xl">{title}</h2></div>{children}</div> }

export function PrimaryButton({ href, children }: { href: string; children: React.ReactNode }) { return <Link href={href} className="inline-flex items-center justify-center gap-2 rounded-full bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground transition hover:brightness-110">{children}<ArrowRight size={16}/></Link> }

export { ArrowRight, Banknote, Building2, Check, ChevronRight, CircleHelp, FileCheck2, Gavel, Handshake, ShieldCheck, Sparkles }
