'use client'
import Link from 'next/link'
import { ArrowRight, Banknote, Check, ChevronRight } from 'lucide-react'
import { useState } from 'react'
import { ConstraintCard, Navbar } from './settlex'

const borrowerFields = [['Loan amount','₹5,00,000'],['Monthly income','₹85,000'],['Essential expenses','₹32,000'],['Existing monthly EMI','₹8,500'],['Maximum affordable EMI','₹16,000'],['Maximum interest rate','14%'],['Preferred tenure','42 months'],['Maximum tenure','60 months']]
const lenderFields = [['Maximum loan amount','₹7,50,000'],['Minimum interest rate','11%'],['Maximum tenure','60 months'],['Minimum expected return','₹1,20,000'],['Collateral requirement','Optional'],['Risk appetite','Moderate']]
export function SetupForm({ lender = false }: { lender?: boolean }) { const [values,setValues]=useState(Object.fromEntries((lender?lenderFields:borrowerFields).map(([k,v])=>[k,v]))); const fields=lender?lenderFields:borrowerFields; return <main className="min-h-screen"><Navbar/><div className="mx-auto grid max-w-7xl gap-8 px-5 pb-20 pt-10 lg:grid-cols-[1.2fr_.8fr] lg:px-8"><div><div className="mb-9"><p className="text-xs font-semibold uppercase tracking-[.22em] text-primary">{lender?'Lender setup':'Borrower setup'} <span className="ml-2 text-muted-foreground">01 / 02</span></p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em]">{lender?'Define your lending boundaries':'Tell us what you need'}</h1><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">{lender?'Set the policy your advocate will protect during the negotiation.':'Give your advocate a clear financial picture. These boundaries stay in your control.'}</p></div><div className="grid gap-5 sm:grid-cols-2">{fields.map(([label,initial])=><label key={label} className="grid gap-2"><span className="text-xs font-medium text-muted-foreground">{label}</span><input value={values[label]} onChange={e=>setValues({...values,[label]:e.target.value})} className="h-12 rounded-xl border border-border bg-white/[.035] px-4 text-sm outline-none transition focus:border-primary/60 focus:ring-2 focus:ring-primary/10"/></label>)}</div>{!lender&&<div className="mt-7"><p className="mb-3 text-xs font-medium text-muted-foreground">Primary priority</p><div className="flex flex-wrap gap-2">{['Low EMI','Low total cost','Flexible repayment','Shorter tenure'].map((option,i)=><button type="button" key={option} className={`rounded-full border px-4 py-2 text-sm ${i===0?'border-primary bg-primary/10 text-primary':'border-border text-muted-foreground'}`}>{option}</button>)}</div></div>}<Link href={lender?'/negotiation':'/lender'} className="mt-9 inline-flex items-center gap-2 rounded-full bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground transition hover:brightness-110">{lender?'Start AI negotiation':'Continue as borrower'}<ArrowRight size={16}/></Link></div><aside className="lg:pt-20"><ConstraintCard title={lender?'Lender constraints':'Your financial boundaries'} items={(lender?lenderFields:borrowerFields).slice(0,6).map(([k,v])=>`${k}:${values[k]}`)}/><div className="mt-4 rounded-2xl border border-primary/15 bg-primary/5 p-5"><div className="flex items-center gap-2 text-sm font-medium"><Banknote size={16} className="text-primary"/> Private by design</div><p className="mt-2 text-xs leading-5 text-muted-foreground">Synthetic prototype data is used for this demo. Your advocate only sees the boundaries you define.</p></div></aside></div></main> }
